name: carlos-ci-action
services:

  carla-simulator:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    privileged: True
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    image: rwthika/carla-simulator:server
    command: bash -ic './CarlaUE4.sh -nosound 2>/dev/null'
